### ISSUE TITLE
--oauth2-password=  cannot contain & character

### ISSUE THREAD

**Issue by michelvankessel** [contabo/cntb#12]
`--oauth2-password=` doesn't accept all special characters.

example 
`--oauth2-password=#3N5646Y4&5%$*7K%wP#BzhP` 

generates the following error
[1] 30820
zsh: command not found: 5%7K%wP#BzhP

`&` is not accepted in my case on MacOS with zsh

Michel

**Comment by Maximilian-Temeschinko** [comment]
Hello michelvankessel,

try setting passwords and other strings with single quotes `'`-symbol around them in order for your shell to not interpret any special characters but to take everything in between the quotes as plain text.

for example try:
```sh
cntb config set-credentials --oauth2-password='#3N5646Y4&5%$*7K%wP#BzhP'
```
this should take the string with `#`-symbol as first and the `P` as last character as your password.

PS: Just to be sure. Please keep in mind that this is a public thread and every password that is written here would not be safe to use anymore.


Best regards
max

**Comment by michelvankessel** [comment]
Thanks for the information @Maximilian-Temeschinko . 

I can confirm that it works by adding the single quotes. Is this mentioned in the documentation? It wasn't very clear to me. 

Thanks for the clarification!

**Comment by Maximilian-Temeschinko** [comment]
It has more to do with how your "shell" / "terminal" / "command line utility" works. In your case `zsh` tries to interpret the `&`-symbol. It is used to send a command to the "background". e.g.: `echo "Hello World!" &` does not print "Hello World!" onto the current active terminal but opens a new process.

So in order to "tell" your shell to not interpret any characters there, we use the quotes. I'm a gnu/linux fanboy so here is the docs of `bash` on this point https://www.gnu.org/software/bash/manual/bash.html#Single-Quotes, but most of the things there also apply to `zsh`.


### caution, overexplanation following ###

From what i can tell what happens when we run:

```sh
cntb config set-credentials --oauth2-password=#3N5646Y4&5%$*7K%wP#BzhP
```
the command:
```sh
cntb config set-credentials --oauth2-password=#3N5646Y4
```

will be executed in the background, then the rest:
```sh
5%$*7K%wP#BzhP
```
will be interpreted as next command where `$*` is also interpreted (https://www.gnu.org/software/bash/manual/bash.html#Single-Quotes) but resolves to empty string

so with the output: "[1] 30820" zsh tells us that it send the command to the background and it got the PID 30820
and the tells us that it does not know any programm called "5%7K%wP#BzhP"

**Comment by michelvankessel** [comment]
thanks for explaining
